***Importing Required Libaries***

In [ ]:
import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction

In [ ]:
def display_format(my_vector, my_decimal): return np.round((my_vector).astype(np.float), decimals=my_decimal)
my_dp = Fraction(1,3)
Mat = np.matrix([[0, 0, 1],
                 [Fraction(1, 2), 0, 0],
                 [Fraction(1, 2), 1, 0]]).astype(float)
Ex = np.zeros((3,3))
Ex[:] = my_dp
beta = 0.7
Al = beta * Mat + ((1-beta) * Ex)
r = np.matrix([my_dp, my_dp, my_dp])
r = np.transpose(r)

In [ ]:
previous_r = r  # Initialize previous_r before the loop
for i in range(1, 100):
    r = Al * r
    print(display_format(r, 3))
    if (previous_r == r).all():
        break
    previous_r = r

[[0.333]
 [0.217]
 [0.45 ]]
[[0.415]
 [0.217]
 [0.368]]
[[0.358]
 [0.245]
 [0.397]]
[[0.378]
 [0.225]
 [0.397]]
[[0.378]
 [0.232]
 [0.39 ]]
[[0.373]
 [0.232]
 [0.395]]
[[0.376]
 [0.231]
 [0.393]]
[[0.375]
 [0.232]
 [0.393]]
[[0.375]
 [0.231]
 [0.394]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [

<ipython-input-6-a88f92500dd4>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def display_format(my_vector, my_decimal): return np.round((my_vector).astype(np.float), decimals=my_decimal)


***Final Output***

In [ ]:
print("Final:\n", display_format(r, 3))
print("sum", np.sum(r))

Final:
 [[0.375]
 [0.231]
 [0.393]]
sum 0.9999999999999951


<ipython-input-6-a88f92500dd4>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def display_format(my_vector, my_decimal): return np.round((my_vector).astype(np.float), decimals=my_decimal)
